MyStockListing.Web/Controllers/InventoryItemsController.cs
using DynamicQueryBuilder;
using DynamicQueryBuilder.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyStockListing.Business.DTOs.Input;
using MyStockListing.Business.DTOs.Output;
using MyStockListing.Business.Services;
using MyStockListing.Web.Models;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace MyStockListing.Web.Controllers
{
    public class InventoryItemsController : Controller
    {
        private readonly ProductService _productService;
        private readonly InventoryItemService _inventoryItemService;
        private readonly WarehouseService _warehouseService;

        public InventoryItemsController(
            InventoryItemService inventoryItemService,
            ProductService productService,
            WarehouseService warehouseService)
        {
            _productService = productService;
            _inventoryItemService = inventoryItemService;
            _warehouseService = warehouseService;
        }

        // GET: InventoryItems
        public IActionResult Index(DynamicQueryOptions dynamicQueryOptions)
        {
            return View();
        }

        // GET: IndexGrid
        [DynamicQuery]
        public IActionResult IndexGrid(DynamicQueryOptions dqbOptions)
        {
            IQueryable<InventoryItemOutputDTO> inventoryItems = _inventoryItemService.GetInventoryItems(dqbOptions);

            return PartialView("_genericGrid", new GenericGridModel
            {
                CRUDActions = true,
                GridId = $"grid-{inventoryItems}",
                Items = inventoryItems,
                SetName = nameof(inventoryItems),
                Columns = new string[]
                {
                    nameof(InventoryItemOutputDTO.Amount),
                    $"{nameof(InventoryItemOutputDTO.ProductName)}",
                    $"{nameof(InventoryItemOutputDTO.Model)}",
                    $"{nameof(InventoryItemOutputDTO.SKU)}",
                    $"{nameof(InventoryItemOutputDTO.WarehouseName)}"
                }
            });
        }

        // GET: InventoryItems/Details/5
        public async Task<IActionResult> Details(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryItem = await _inventoryItemService.GetInventoryItemByIdAsync(id.Value, cancellationToken);
            if (inventoryItem == null)
            {
                return NotFound();
            }

            return View(inventoryItem);
        }

        // GET: InventoryItems/Create
        public IActionResult Create()
        {
            SetViewDataWithProductsAndWarehouses(null, null);
            return View();
        }

        // POST: InventoryItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Amount,ReservedAmount,ProductId,WarehouseId")] InventoryItemInputDTO inventoryItem, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _inventoryItemService.CreateInventoryItemAsync(inventoryItem, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View(inventoryItem);
        }

        // GET: InventoryItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryItem = await _inventoryItemService.GetInventoryItemByIdAsync(id.Value, cancellationToken);
            if (inventoryItem == null)
            {
                return NotFound();
            }

            SetViewDataWithProductsAndWarehouses(inventoryItem.Product.Id, inventoryItem.Warehouse.Id);
            return View(inventoryItem);
        }

        // POST: InventoryItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Amount,ProductId,WarehouseId")] InventoryItemInputDTO inventoryItem, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _inventoryItemService.UpdateInventoryItem(id, inventoryItem, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            SetViewDataWithProductsAndWarehouses(inventoryItem.ProductId, inventoryItem.WarehouseId);
            return View(inventoryItem);
        }

        // GET: InventoryItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryItem = await _inventoryItemService.GetInventoryItemByIdAsync(id.Value, cancellationToken);
            if (inventoryItem == null)
            {
                return NotFound();
            }

            return View(inventoryItem);
        }

        // POST: InventoryItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id, CancellationToken cancellationToken)
        {
            await _inventoryItemService.DeleteProductAsync(id, false, cancellationToken);
            return RedirectToAction(nameof(Index));
        }

        private void SetViewDataWithProductsAndWarehouses(Guid? selectedProductId, Guid? selectedWarehouseId)
        {
            ViewData["ProductId"] = new SelectList(_productService.GetProducts(null), "Id", "Name", selectedProductId);
            ViewData["WarehouseId"] = new SelectList(_warehouseService.GetWarehouses(null, 0, 0), "Id", "Name", selectedWarehouseId);
        }
    }
}

MyStockListing.Web/Controllers/ProductsController.cs
using DynamicQueryBuilder;
using DynamicQueryBuilder.Models;
using Microsoft.AspNetCore.Mvc;
using MyStockListing.Business.DTOs.Input;
using MyStockListing.Business.DTOs.Output;
using MyStockListing.Business.Services;
using MyStockListing.Web.Models;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace MyStockListing.Web.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductService _productService;

        public ProductsController(ProductService productService)
        {
            _productService = productService;
        }

        // GET: Products
        [DynamicQuery]
        public IActionResult Index()
        {
            return View();
        }

        // GET: Products
        [DynamicQuery]
        public IActionResult IndexGrid(DynamicQueryOptions dynamicQueryOptions)
        {
            IQueryable<ProductOutputDTO> products = _productService.GetProducts(dynamicQueryOptions);

            return PartialView("_genericGrid", new GenericGridModel
            {
                CRUDActions = true,
                GridId = $"grid-{nameof(products)}",
                Items = products,
                SetName = nameof(products),
                Columns = new string[]
                {
                    nameof(ProductOutputDTO.SKU),
                    nameof(ProductOutputDTO.Name),
                    nameof(ProductOutputDTO.Brand),
                    nameof(ProductOutputDTO.Model),
                    nameof(ProductOutputDTO.CreatedAt)
                }
            });
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _productService.GetProductByIdAsync(id.Value, cancellationToken);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Brand,Model,SKU")] ProductInputDTO product, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                ProductOutputDTO result = await _productService.CreateProductAsync(product, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _productService.GetProductByIdAsync(id.Value, cancellationToken);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,Brand,Model,SKU")] ProductInputDTO product, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _productService.UpdateProductAsync(id, product, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _productService.GetProductByIdAsync(id.Value, cancellationToken);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id, CancellationToken cancellationToken)
        {
            await _productService.DeleteProductAsync(id, false, cancellationToken);
            return RedirectToAction(nameof(Index));
        }
    }
}

MyStockListing.Web/Controllers/WarehousesController.cs
using DynamicQueryBuilder;
using DynamicQueryBuilder.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyStockListing.Business.DTOs.Input;
using MyStockListing.Business.DTOs.Output;
using MyStockListing.Business.Services;
using MyStockListing.Web.Models;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace MyStockListing.Web.Controllers
{
    public class WarehousesController : Controller
    {
        private readonly LocationService _locationService;
        private readonly WarehouseService _warehouseService;

        public WarehousesController(WarehouseService warehouseService, LocationService locationService)
        {
            _locationService = locationService;
            _warehouseService = warehouseService;
        }

        // GET: Warehouses
        [DynamicQuery]
        public IActionResult Index(DynamicQueryOptions dynamicQueryOptions)
        {
            return View(_warehouseService.GetWarehouses(dynamicQueryOptions, 0, 0));
        }

        // GET: Warehouses
        [DynamicQuery]
        public IActionResult IndexGrid(DynamicQueryOptions dqbOptions, double longitude, double latitude)
        {
            IQueryable<WarehouseOutputDTO> warehouses = _warehouseService.GetWarehouses(dqbOptions, longitude, latitude);

            return PartialView("_genericGrid", new GenericGridModel
            {
                CRUDActions = true,
                GridId = $"grid-{warehouses}",
                Items = warehouses,
                SetName = nameof(warehouses),
                Columns = new string[]
                {
                    nameof(WarehouseOutputDTO.Name),
                    nameof(WarehouseOutputDTO.Address),
                    nameof(WarehouseOutputDTO.Coordinates)
                }
            });
        }

        // GET: Warehouses/Details/5
        public async Task<IActionResult> Details(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetWarehouseByIdAsync(id.Value, cancellationToken);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // GET: Warehouses/Create
        public IActionResult Create()
        {
            var countries = _locationService.GetAllCountries().ToList();
            ViewData["countries"] = new SelectList(countries, "Id", "Name");
            ViewData["cities"] = new SelectList(countries.SelectMany(x => x.Cities), "Id", "Name");
            return View();
        }

        // POST: Warehouses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,DistrictId,Coordinates,Latitude,Longitude")] WarehouseInputDTO warehouse, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _warehouseService.CreateWarehouseAsync(warehouse, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Edit/5
        public async Task<IActionResult> Edit(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetWarehouseByIdAsync(id.Value, cancellationToken);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // POST: Warehouses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,DistrictId,Coordinates")] WarehouseInputDTO warehouse, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                await _warehouseService.UpdateWarehouseAsync(id, warehouse, cancellationToken);
                return RedirectToAction(nameof(Index));
            }

            return View(warehouse);
        }

        // GET: Warehouses/Delete/5
        public async Task<IActionResult> Delete(Guid? id, CancellationToken cancellationToken)
        {
            if (id == null)
            {
                return NotFound();
            }

            var warehouse = await _warehouseService.GetWarehouseByIdAsync(id.Value, cancellationToken);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id, CancellationToken cancellationToken)
        {
            await _warehouseService.DeleteProductAsync(id, false, cancellationToken);
            return RedirectToAction(nameof(Index));
        }
    }
}

MyStockListing.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyStockListing.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>

    <link rel="stylesheet" href="~/css/mvc-grid.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyStockListing.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InventoryItems" asp-action="Index">Inventories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouses" asp-action="Index">Warehouses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MyStockListing.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/mvc-grid.js" asp-append-version="true"></script>
    <script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MyStockListing.Web/Views/Shared/_genericGrid.cshtml
@model GenericGridModel
@* Should only include grid declaration *@

@(Html.Grid(Model.Items)
              .Build(columns =>
              {
                  if (Model.Items != null && Model.Items.Count() > 0)
                  {
                      var props = Model.Items
                          .ElementAt(0)
                          .GetType()
                          .GetProperties()
                          .Where(x => Model.Columns.Contains(x.Name));

                      foreach (var item in props)
                      {
                          columns.Add(model => item.GetValue(model)).Sortable(true).FilteredAs("custom").Titled(item.Name);
                      }

                      if (Model.CRUDActions)
                      {
                          var idProp = Model.Items.ElementAt(0).GetType().GetProperty("Id");
                          columns.Add().Encoded(false).RenderedAs(model => $"<a href='/{Model.SetName}/Edit/{@idProp.GetValue(model)}'>Edit</a> | <a href='/{Model.SetName}/Delete/{@idProp.GetValue(model)}'>Delete</a>");
                      }
                  }
              }).Empty("No data found")
                    .Id(Model.GridId)
                    .Pageable(pager =>
                    {
                        pager.PagesToDisplay = 2;
                        pager.RowsPerPage = 10;
                    })
                    .Filterable()
                    .Sortable())